---
## Tenant vlans start at 10
## one for each application tier (3 total)
## one for shared and edge routing (2 total)
## Example:
## Tenant 1 = 10-12
## Tenant 2 = 15-17
## Tenant 3 = 20-22

########## Update for new Tenants #############

tenant_vlans:
  - tenant: tenant1
    number: 10
    name: web 
    vni: 10010
  - tenant: tenant1
    number: 11
    name: app
    vni: 10011
  - tenant: tenant1
    number: 12
    name: db
    vni: 10012
  - tenant: tenant1
    number: 13
    name: edge
    vni: 10013
  - tenant: tenant1
    number: 14
    name: shared
    vni: 10014
  - tenant: tenant2
    number: 15
    name: web
    vni: 10015
  - tenant: tenant2
    number: 16
    name: app
    vni: 10016
  - tenant: tenant2
    number: 17
    name: db
    vni: 10017
  - tenant: tenant2
    number: 18
    name: edge
    vni: 10018
  - tenant: tenant1
    number: 19
    name: shared
    vni: 10019

###############################################
