---
########## Update for new Tenants #############

tenant_vlans:
  - tenant: tenant1
    number: 10
    name: web 
    vni: 10010
  - tenant: tenant1
    number: 11
    name: app
    vni: 10011
  - tenant: tenant1
    number: 12
    name: db
    vni: 10012

###############################################
